name: README CHECK

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  build:
    name: README Check
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.13.4]
        java: [adopt@1.15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}

      - shell: bash
        run: ./check-docs.sh || true
